apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-{{ .Values.environment }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}